Director {
  Name        = bareos-dir
  DIRport     = 9101
  QueryFile   = "/usr/lib/bareos/scripts/query.sql"
  WorkingDirectory = "/var/lib/bareos"
  PidDirectory     = "/run/bareos"
  Maximum Concurrent Jobs = 10
  Password    = "@BAREOS_DIRECTOR_PASSWORD@"
  Messages    = Daemon
}

Catalog {
  Name       = MyCatalog
  dbname     = "bareos"
  dbuser     = "@POSTGRES_USER@"
  dbpassword = "@POSTGRES_PASSWORD@"
  dbaddress  = "postgres"
  dbport     = 5432
}

Messages {
  Name    = Standard
  console = all, !skipped, !restored
  catalog = all
}

Messages {
  Name    = Daemon
  console = all, !skipped, !saved, !restored
}

Pool {
  Name           = Default
  Pool Type      = Backup
  Recycle        = yes
  AutoPrune      = yes
  Volume Retention = 180 days
  Maximum Volumes  = 3
  Label Format   = "VOL-DEFAULT-"
}

Pool {
  Name      = Scratch
  Pool Type = Scratch
}

@|"sh -c 'for f in /etc/bareos/bareos-dir.d/*.conf; do echo @${f}; done'"
