# Produzione
#Storage {
#  Name = File-Storage-prod
#  Address  = bareos-storage
#  Password = "@env:DIRECTOR_PASSWORD"
#  Device   = TapeDevice
#  Media Type = LTO
#}

# Sviluppo
Storage {
  Name = File-Storage-dev
  Address  = bareos-storage
  Password = "@env:DIRECTOR_PASSWORD"
  Device   = VirtualTapeDevice
  Media Type = File
}