message(STATUS "Python3_CC is  x86_64-linux-gnu-gcc")
set(Python3_CC "x86_64-linux-gnu-gcc")
message(STATUS "Python3_CC_FLAGS is  ")
set(Python3_CC_FLAGS "")
message(STATUS "Python3_BLDSHARED is  x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions  -Wl,-z,relro -g -fwrapv -O2   ")
set(Python3_BLDSHARED "x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions  -Wl,-z,relro -g -fwrapv -O2   ")
message(STATUS "Python3_BLDSHARED_FLAGS is  -shared -Wl,-O1 -Wl,-Bsymbolic-functions  -Wl,-z,relro -g -fwrapv -O2   ")
set(Python3_BLDSHARED_FLAGS "-shared -Wl,-O1 -Wl,-Bsymbolic-functions  -Wl,-z,relro -g -fwrapv -O2   ")
message(STATUS "Python3_CFLAGS is -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall")
set(Python3_CFLAGS "-fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall")
message(STATUS "Python3_CCSHARED is -fPIC")
set(Python3_CCSHARED "-fPIC")
message(STATUS "Python3_INCLUDEPY is /usr/include/python3.13")
set(Python3_INCLUDEPY "/usr/include/python3.13")
message(STATUS "Python3_LDFLAGS is  -Wl,-z,relro -g -fwrapv -O2   ")
set(Python3_LDFLAGS " -Wl,-z,relro -g -fwrapv -O2   ")
message(STATUS "Python3_EXT_SUFFIX is .cpython-313-x86_64-linux-gnu.so")
set(Python3_EXT_SUFFIX ".cpython-313-x86_64-linux-gnu.so")
